### ISSUE TITLE
Why does this need a GET request and open up the app to CSRF attacks?

### ISSUE THREAD

**Issue by Bartvds** [django-hijack/django-hijack-admin#7]
I'm kinda curious why this was an acceptable choice?

How do we use `django-hijack` without this?

(I read https://github.com/arteria/django-hijack/issues/84)

**Comment by Bartvds** [comment]
I got a hacky fix working, simply by overriding the button template to submit a form instead of being a plain link.

Implementation is a little ugly because it seems we need to create this form in JavaScript because the whole changelist is a form and nesting forms is a bit funky. But if you create the form in javascript on-click it seems to work (in my Firefox). 

Then I can put HIJACK_ALLOW_GET_REQUESTS back to False and silence the django-hijack-admin check with Django's SILENCED_SYSTEM_CHECKS feature.

Is it worth it to make this solution nice and add it to the package? Main thing it needs it a place to put a shared snippet of JavaScript but ideally without users having to override their changelist templates (in this ugly version the snippet repeats on every row).

**Comment by jvamvas** [comment]
You are right @Bartvds, CSRF protection is an important issue. That's why from version 2.1, we have moved the Django admin integration into a separate package – to give users a choice whether or not to allow GET requests.

There are other ways to integrate django-hijack into your project. If, for instance, you have your own admin interface, then you could place the hijack form there. Here's a reference implementation: https://django-hijack.readthedocs.io/en/latest/#usage

However, if you find a way to use a form in the admin instead of a button – and the solution is both maintainable and non-hacky – that would of course be great and we would be happy to review a pull request! :)

**Comment by radyz** [comment]
If old browser support is not required you could add it as a button in your model admin as:

`return format_html(mark_safe("""
             <input type="submit" formaction="/hijack/{}/" value="Hijack" />
  """), obj.id)`

**Comment by andybak** [comment]
Any thoughts on this? The solution above looks pretty acceptable to be. I'll admit I have a tendency to use GET in my own changelist customisations but it's probably not good to promote this in a reusable app.

**Comment by jonashaag** [comment]
I'm interested in this too.

**Comment by Bartvds** [comment]
It is waiting for a PR I guess.

I personally think a POST with CSRF protection should be the default implementation as there is (AFAIK) no real reason to use GET (besides implementation convenience).

I like @radyz  `formaction` based approach, browser support is fair http://caniuse.com/#search=formaction

**Comment by radyz** [comment]
If using ```formaction``` is acceptable I could issue a PR for this.

**Comment by Bartvds** [comment]
Maybe it would need a setting to toggle the `formaction` approach as an escape for users where browser support is problematic. 

We could also require to explicitly enable this feature so we wouldn't need a major version bump on release (because it is a breaking change for old browsers), but I'm not sure if that matters enough.

**Comment by nsaje** [comment]
Hey guys, I think I solved this in https://github.com/arteria/django-hijack-admin/pull/37 .
